# 多语言支持字典

LANGUAGES = {
    "zh_CN": {  # 简体中文
        "language_name": "简体中文",
        "app_title": "AI代码上下文助手",
        "settings": "设置",
        "dir_path": "目录路径:",
        "browse": "浏览...",
        "show_hidden": "显示隐藏文件",
        "show_files": "显示文件",
        "show_folders": "显示文件夹",
        "preserve_tree": "固定目录树",
        "use_relative_path": "使用相对路径",
        "max_depth": "最大深度:",
        "file_filter": "文件过滤:",
        "reset": "重置",
        "copy_tree": "复制目录树",
        "save_to_file": "保存到文件",
        "dir_tree": "目录树",
        "format_settings": "设置文本格式",
        "path_prefix": "路径前缀:",
        "path_suffix": "路径后缀:",
        "code_prefix": "代码前缀:",
        "code_suffix": "代码后缀:",
        "note": "注意:\n• 推荐使用Markdown代码块格式(```)\n• 这种格式最适合与AI助手交互\n• 可使用\\n表示换行",
        "save": "保存",
        "cancel": "取消",
        "ready": "就绪",
        "status_tree_generated": "完成: 已生成 {0} 的目录树",
        "error_invalid_dir": "错误: 请选择有效的目录",
        "error_permission_denied": "[权限被拒绝]",
        "error_msg": "[错误: {0}]",
        "expand_all": "完全展开",
        "copy_path_and_code": "复制路径与代码",
        "copy_path": "复制路径",
        "copy_code": "复制代码",
        "copy_filename": "复制文件名",
        "status_copied_to_clipboard": "已复制到剪贴板",
        "status_no_selection": "错误: 没有选中内容可复制",
        "status_saved_to": "已保存到 {0}",
        "status_save_failed": "保存失败: {0}",
        "status_paths_copied": "已复制 {0} 个路径",
        "status_no_paths": "没有可用的文件路径",
        "status_code_copied": "已复制 {0} 个文件的代码",
        "status_no_text_files": "没有可读的文本文件",
        "status_path_code_copied": "已复制 {0} 个文件的路径和代码",
        "status_filenames_copied": "已复制 {0} 个文件名",
        "language": "语言:",
        "format_text_updated": "已更新文本格式设置",
        "remove_from_history": '删除 "{0}"',
        "clear_history": "清空全部历史",
        "no_history": "无历史记录",
        "status_history_removed": "已从历史记录中删除: {0}",
        "status_history_cleared": "已清空所有历史记录",
        "tooltip_status_bar": "显示操作状态和结果",
        "tooltip_dir_path": "选择要生成目录树的文件夹路径",
        "tooltip_browse": "打开文件夹选择对话框",
        "tooltip_show_hidden": "显示以点(.)开头的隐藏文件和文件夹\n在Windows上还包括设置了隐藏属性的文件",
        "tooltip_show_files": "在目录树中显示文件\n取消勾选则只显示文件夹",
        "tooltip_show_folders": "在目录树中显示文件夹\n取消勾选则只显示文件",
        "tooltip_preserve_tree": "重置时保留当前目录树的展开/收起状态和勾选状态\n同时更新文件系统的变化，如新增或删除的文件",
        "tooltip_use_relative": "复制文件路径时使用相对于所选根目录的路径\n而不是绝对路径",
        "tooltip_format_settings": "设置复制文件路径和代码时的文本格式\n包括前缀和后缀",
        "tooltip_max_depth": "限制目录树显示的最大层级深度\n0表示不限制深度",
        "tooltip_spinbox": "设置目录树显示的最大层级深度\n0表示不限制深度",
        "tooltip_file_filter": "使用正则表达式过滤显示的文件\n只有文件名匹配表达式的文件才会显示\n例如: \\.py$ 只显示Python文件",
        "tooltip_reset": '重新加载目录树\n如果勾选了"固定目录树"，将保留展开/收起状态和勾选状态',
        "tooltip_copy_tree": "将当前目录树的可视结构复制到剪贴板",
        "tooltip_save_file": "将当前目录树的可视结构保存到文本文件",
        "tooltip_prefix_entry": "可使用\\n表示换行",
        "tooltip_suffix_entry": "可使用\\n表示换行",
        "tooltip_save_btn": "保存文本格式设置",
        "tooltip_cancel_btn": "取消修改并关闭窗口",
        "generating_tree": "正在生成目录树...",
        "load_settings_failed": "加载设置失败: {0}",
        "save_settings_failed": "保存设置失败: {0}",
    },
    "en_US": {  # 英文
        "language_name": "English",
        "app_title": "AI Code Context Helper",
        "settings": "Settings",
        "dir_path": "Directory Path:",
        "browse": "Browse...",
        "show_hidden": "Show Hidden Files",
        "show_files": "Show Files",
        "show_folders": "Show Folders",
        "preserve_tree": "Preserve Tree State",
        "use_relative_path": "Use Relative Path",
        "max_depth": "Max Depth:",
        "file_filter": "File Filter:",
        "reset": "Reset",
        "copy_tree": "Copy Tree",
        "save_to_file": "Save to File",
        "dir_tree": "Directory Tree",
        "format_settings": "Text Format Settings",
        "path_prefix": "Path Prefix:",
        "path_suffix": "Path Suffix:",
        "code_prefix": "Code Prefix:",
        "code_suffix": "Code Suffix:",
        "note": "Note:\n• Markdown code block format (```) is recommended\n• This format works best with AI assistants\n• You can use \\n for line breaks",
        "save": "Save",
        "cancel": "Cancel",
        "ready": "Ready",
        "status_tree_generated": "Done: Tree generated for {0}",
        "error_invalid_dir": "Error: Please select a valid directory",
        "error_permission_denied": "[Permission Denied]",
        "error_msg": "[Error: {0}]",
        "expand_all": "Expand All",
        "copy_path_and_code": "Copy Path and Code",
        "copy_path": "Copy Path",
        "copy_code": "Copy Code",
        "copy_filename": "Copy Filename",
        "status_copied_to_clipboard": "Copied to clipboard",
        "status_no_selection": "Error: No selection to copy",
        "status_saved_to": "Saved to {0}",
        "status_save_failed": "Save failed: {0}",
        "status_paths_copied": "Copied {0} paths",
        "status_no_paths": "No file paths available",
        "status_code_copied": "Copied code from {0} files",
        "status_no_text_files": "No readable text files",
        "status_path_code_copied": "Copied paths and code from {0} files",
        "status_filenames_copied": "Copied {0} filenames",
        "language": "Language:",
        "format_text_updated": "Text format settings updated",
        "remove_from_history": 'Remove "{0}"',
        "clear_history": "Clear All History",
        "no_history": "No History",
        "status_history_removed": "Removed from history: {0}",
        "status_history_cleared": "All history cleared",
        "tooltip_status_bar": "Shows operation status and results",
        "tooltip_dir_path": "Select folder to generate directory tree",
        "tooltip_browse": "Open folder selection dialog",
        "tooltip_show_hidden": "Show hidden files and folders starting with dot (.)\nOn Windows also includes files with hidden attribute",
        "tooltip_show_files": "Show files in the directory tree\nUncheck to show only folders",
        "tooltip_show_folders": "Show folders in the directory tree\nUncheck to show only files",
        "tooltip_preserve_tree": "Preserve expand/collapse and check states when resetting\nWhile updating changes in the filesystem",
        "tooltip_use_relative": "Use paths relative to the selected root directory\nInstead of absolute paths",
        "tooltip_format_settings": "Set text format for copying file paths and code\nIncluding prefixes and suffixes",
        "tooltip_max_depth": "Limit the maximum depth level of the directory tree\n0 means no depth limit",
        "tooltip_spinbox": "Set the maximum depth level of the directory tree\n0 means no depth limit",
        "tooltip_file_filter": "Filter files using regular expressions\nOnly files matching the pattern will be shown\nExample: \\.py$ to show only Python files",
        "tooltip_reset": "Reload the directory tree\nIf 'Preserve Tree State' is checked, will keep expand/collapse and check states",
        "tooltip_copy_tree": "Copy the visual structure of the directory tree to clipboard",
        "tooltip_save_file": "Save the visual structure of the directory tree to a text file",
        "tooltip_prefix_entry": "You can use \\n for line breaks",
        "tooltip_suffix_entry": "You can use \\n for line breaks",
        "tooltip_save_btn": "Save text format settings",
        "tooltip_cancel_btn": "Cancel changes and close window",
        "generating_tree": "Generating directory tree...",
        "load_settings_failed": "Failed to load settings: {0}",
        "save_settings_failed": "Failed to save settings: {0}",
    },
}
